/*
 * Copyright (C) 2022-2023 Luke Bemish and contributors
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */

package dev.lukebemish.dynamicassetgenerator.api.client.generators;

import com.google.gson.JsonElement;
import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.datafixers.util.Pair;
import com.mojang.serialization.Codec;
import com.mojang.serialization.DataResult;
import com.mojang.serialization.DynamicOps;
import com.mojang.serialization.JsonOps;
import dev.lukebemish.dynamicassetgenerator.api.ResourceGenerationContext;
import dev.lukebemish.dynamicassetgenerator.api.cache.CacheMetaCodec;
import dev.lukebemish.dynamicassetgenerator.api.cache.DataConsumer;
import dev.lukebemish.dynamicassetgenerator.impl.DynamicAssetGenerator;
import dev.lukebemish.dynamicassetgenerator.impl.client.ClientRegisters;
import dev.lukebemish.dynamicassetgenerator.impl.client.TexSourceCachingWrapper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.IoSupplier;
import net.minecraft.util.ExtraCodecs;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.function.Function;

public interface TexSource {

    String METADATA_CACHE_KEY = "__dynamic_asset_generator_metadata";
    Codec<TexSource> CODEC = CacheMetaCodec.of(ExtraCodecs.lazyInitializedCodec(() -> new Codec<Codec<? extends TexSource>>() {
        @Override
        public <T> DataResult<Pair<Codec<? extends TexSource>, T>> decode(DynamicOps<T> ops, T input) {
            return ResourceLocation.CODEC.decode(ops, input).flatMap(keyValuePair -> !ClientRegisters.TEXSOURCES.containsKey(keyValuePair.getFirst())
                    ? DataResult.error(() -> "Unknown dynamic texture source type: " + keyValuePair.getFirst())
                    : DataResult.success(keyValuePair.mapFirst(ClientRegisters.TEXSOURCES::get)));
        }

        @Override
        public <T> DataResult<T> encode(Codec<? extends TexSource> input, DynamicOps<T> ops, T prefix) {
            ResourceLocation key = ClientRegisters.TEXSOURCES.inverse().get(input);
            if (key == null) {
                return DataResult.error(() -> "Unregistered dynamic texture source type: " + input);
            }
            T toMerge = ops.createString(key.toString());
            return ops.mergeToPrimitive(prefix, toMerge);
        }
    }).dispatch(TexSource::codec, Function.identity()).xmap(TexSource::cached, wrapped -> {
        while (wrapped instanceof TexSourceCachingWrapper cachingWrapper) {
            wrapped = cachingWrapper.wrapped();
        }
        return wrapped;
    }), new DataConsumer<>() {
        @Override
        @NotNull
        public <T1> DataResult<T1> encode(DynamicOps<T1> ops, TexSourceDataHolder data, TexSource object) {
            return object.cacheMetadata(ops, data);
        }
    }, METADATA_CACHE_KEY, TexSourceDataHolder.class);

    static <T extends TexSource> void register(ResourceLocation rl, Codec<T> codec) {
        ClientRegisters.TEXSOURCES.put(rl, codec);
    }

    /**
     * If your texture source depends on runtime data context (anything stored in the {@link TexSourceDataHolder}), you will
     * need to override this method to return a unique key for the given context. This key will be used when caching
     * textures generated by this source. If your source should not be cached, return a DataResult.error.
     * @param ops DynamicOps to encode the unique key with.
     * @param data Data holder that the key is dependent on.
     * @return A success with a unique key for the given context, or an error if no key can be generated.
     */
    @NotNull @ApiStatus.Experimental
    default <T> DataResult<T> cacheMetadata(DynamicOps<T> ops, TexSourceDataHolder data) {
        return DataResult.success(ops.empty());
    }

    Codec<? extends TexSource> codec();

    @Nullable
    IoSupplier<NativeImage> getSupplier(TexSourceDataHolder data, ResourceGenerationContext context);

    @ApiStatus.Experimental
    default TexSource cached() {
        if (this instanceof TexSourceCachingWrapper) return this;
        return new TexSourceCachingWrapper(this);
    }

    /**
     * @return a string representation of this texture source, meant for logging and debugging purposes. Should
     * <em>not</em> be used for serialization or caching. Can be safely overridden to provide whatever information
     * is deemed useful.
     */
    default String stringify() {
        JsonElement element = CODEC.encodeStart(JsonOps.INSTANCE, this).result().orElse(null);
        if (element == null) return this.toString();
        return DynamicAssetGenerator.GSON_FLAT.toJson(element);
    }
}
